services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d tasks']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped




  mongo:
     image: mongo:latest
     container_name: mongo
     ports:
      - "27017:27017"
     environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
     volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: